const teams = [
    {
        "nome": "Athletico-PR",
        "alcunha": "Furacão da Baixada",
        "anoInauguracao": "26 de março de 1924 (100 anos)",
        "presidenteTime": "Mario Celso Petraglia",
        "treinadorAtual": "Martín Varini",
        "nomeEstadio": "Ligga Arena (Estádio Mário Celso Petraglia)",
        "capacidade": 42372,
        "mascote": "Furacão",
        "historia": "O Athletico Paranaense, conhecido como Furacão, é um clube de futebol de Curitiba fundado em 1924. Com uma história marcada por conquistas estaduais e nacionais, o clube destaca-se pela paixão de sua torcida e pelo estádio Arena da Baixada. O Athletico é conhecido pela sua forte presença no futebol paranaense e pelas suas recentes vitórias na Copa Sul-Americana e na Copa do Brasil.",
        "linkHino": "https://www.letras.mus.br/hinos-de-futebol/76325/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Club_Athletico_Paranaense",
        "linkSabiaMais": "https://www.transfermarkt.com.br/club-athletico-paranaense/startseite/verein/679",
        "titulos": {
            "estadual": 27,
            "nacional": 2,
            "internacional": 2
        },
        "imagemTime": "img/brasil_logos/ath_paranense.png", 
        "imagemEstadio": "img/brasil_estadios/ath_paranense_estadio.png",   
        "imagemMascote": "img/brasil_mascote/ath_paranense_mascote.png"  
    },    
    {
        "nome": "Atlético-GO",
        "alcunha": "Dragão Campineiro",
        "anoInauguracao": "2 de abril de 1937 (87 anos)",
        "presidenteTime": "Adson Batista",
        "treinadorAtual": "Umberto Louzer",
        "nomeEstadio": "Castelo do Dragão (Estádio Antônio Accioly)",
        "capacidade": 12500,
        "mascote": "Dragão",
        "historia": "O Atlético Goianiense, ou Dragão, é um time de Goiás fundado em 1937. O clube tem uma trajetória de respeito no futebol goiano e nacional, com vários títulos estaduais e uma presença constante nas divisões principais do Campeonato Brasileiro. O Dragão é conhecido pelo seu estádio, o Estádio Antônio Accioly, e pela sua torcida vibrante.",
        "linkHino": "https://www.letras.mus.br/hinos-de-futebol/1699541/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Atl%C3%A9tico_Clube_Goianiense",
        "linkSabiaMais": "https://www.transfermarkt.com.br/atletico-clube-goianiense/startseite/verein/15172",
        "titulos": {
            "estadual": 15,
            "nacional": 1,
            "internacional": 0
        },
        "imagemTime": "img/brasil_logos/atl_goianiense.png", 
        "imagemEstadio": "img/brasil_estadios/atl_goianiense_estadio.png",   
        "imagemMascote": "img/brasil_mascote/atl_goianiense_mascote.png"  
    },
    {
        "nome": "Atlético-MG",
        "alcunha": "Galo Doido",
        "anoInauguracao": "25 de março de 1908 (116 anos)",
        "presidenteTime": "Sérgio Coelho",
        "treinadorAtual": "Gabriel Milito",
        "nomeEstadio": "Arena MRV (Estádio do Atlético Mineiro)",
        "capacidade": 46000,
        "mascote": "Galo",
        "historia": "O Atlético Mineiro, também conhecido como Galo, é um dos clubes mais tradicionais do futebol brasileiro, fundado em 1908. Com uma rica história de conquistas, o clube possui diversos títulos estaduais e nacionais, além de uma Copa Libertadores. O Atlético é famoso pela paixão de sua torcida e pelo estádio Mineirão, em Belo Horizonte.",
        "linkhino": "https://www.letras.mus.br/hinos-de-futebol/46358/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Clube_Atl%C3%A9tico_Mineiro",
        "linkSabiaMais": "https://www.transfermarkt.com.br/clube-atletico-mineiro/startseite/verein/330",
        "titulos": {
            "estadual": 47,
            "nacional": 8,
            "internacional": 2
        },
        "imagemTime": "img/brasil_logos/atl_mineiro.png", 
        "imagemEstadio": "img/brasil_estadios/atl_mineiro_estadio.png",
        "imagemMascote": "img/brasil_mascote/atl_mineiro_mascote.png"  
    },        
    {
        "nome": "Avaí",
        "alcunha": "Leão da Ilha",
        "anoInauguracao": "1 de setembro de 1923 (101 anos)",
        "presidenteTime": "Francisco José Battistotti",
        "treinadorAtual": "Enderson Moreira",
        "nomeEstadio": "Ressacada (Estádio Aderbal Ramos da Silva",
        "capacidade": 17826,
        "mascote": "Leão",
        "historia": "O Avaí Futebol Clube, fundado em 1923, é um dos principais times de Santa Catarina. Conhecido pelo apelido de Leão da Ilha, o Avaí tem uma base de torcedores fiel e realiza suas partidas no Estádio da Ressacada. O clube tem uma história rica no futebol catarinense e participa frequentemente da Série A do Campeonato Brasileiro.",
        "linkhino": "https://www.letras.mus.br/hinos-de-futebol/136563/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Ava%C3%AD_Futebol_Clube",
        "linkSabiaMais": "https://www.transfermarkt.com.br/avai-fc-sc-/startseite/verein/2035",
        "titulos": {
            "estadual": 17,
            "nacional": 0,
            "internacional": 0
        },
        "imagemTime": "img/brasil_logos/avai.png", 
        "imagemEstadio": "img/brasil_estadios/avai_estadio.png",   
        "imagemMascote": "img/brasil_mascote/avai_mascote.png"  
    },    
    {
        "nome": "Bahia",
        "alcunha": "Bahêa, Tricolor de Aço",
        "anoInauguracao": "1 de janeiro de 1931 (93 anos)",
        "presidenteTime": "Emerson Ferretti",
        "treinadorAtual": "Rogério Ceni",
        "nomeEstadio": "Arena Fonte Nova (Estádio do Bahia)",
        "capacidade": 50025,
        "mascote": "Super-Homem",
        "historia": "O Esporte Clube Bahia, fundado em 1931, é um dos clubes mais tradicionais da Bahia e do Brasil. Com uma história rica, o Bahia possui títulos nacionais e estaduais, destacando-se pela sua torcida apaixonada e pelo estádio Fonte Nova. O clube é conhecido pelo seu forte impacto no futebol nordestino e pelas suas conquistas ao longo das décadas.",
        "linkhino": "https://www.letras.mus.br/hinos-de-futebol/125156/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Esporte_Clube_Bahia",
        "linkSabiaMais": "https://www.transfermarkt.com.br/esporte-clube-bahia/startseite/verein/10010",
        "titulos": {
            "estadual": 48,
            "nacional": 2,
            "internacional": 0
        },
        "imagemTime": "img/brasil_logos/bahia.png", 
        "imagemEstadio": "img/brasil_estadios/bahia_estadio.png",   
        "imagemMascote": "img/brasil_mascote/bahia_mascote.png"  
    },  
    {
        "nome": "Botafogo",
        "alcunha": "Glorioso",
        "anoInauguracao": "12 de agosto de 1904 (120 anos)",
        "presidenteTime": "Durcésio Mello",
        "treinadorAtual": "Artur Jorge",
        "nomeEstadio": "Engenhão ou Niltão (Estádio Olímpico Nilton Santos)",
        "capacidade": 46831,
        "mascote": "Biriba",
        "historia": "O Botafogo de Futebol e Regatas, fundado em 1904, é um dos clubes mais tradicionais do Rio de Janeiro. Com uma rica história de conquistas, o Botafogo possui diversos títulos estaduais e nacionais, além de ser conhecido por sua torcida apaixonada. O clube manda seus jogos no Estádio Nilton Santos, também conhecido como Engenhão.",
        "linkhino": "https://www.letras.mus.br/botafogo/1202922/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Botafogo_de_Futebol_e_Regatas",
        "linkSabiaMais": "https://www.transfermarkt.com.br/botafogo-rio-de-janeiro/startseite/verein/537",
        "titulos": {
            "estadual": 22,
            "nacional": 2,
            "internacional": 1
        },
        "imagemTime": "img/brasil_logos/botafogo.png", 
        "imagemEstadio": "img/brasil_estadios/botafogo_estadio.png",   
        "imagemMascote": "img/brasil_mascote/botafogo_mascote.png"  
    },
    {
        "nome": "Bragantino",
        "alcunha": "Massa Bruta",
        "anoInauguracao": "8 de janeiro de 1928 (96 anos)",
        "presidenteTime": "Diego Cerri",
        "treinadorAtual": "Pedro Caixinha",
        "nomeEstadio": "Nabizão (Estádio Nabi Abi Chedid)",
        "capacidade": 15010,
        "mascote": "Toro Loko",
        "historia": "O Red Bull Bragantino, fundado em 1928 e atualmente sob a gestão da Red Bull, é um time tradicional do interior de São Paulo. Com um passado marcado por conquistas estaduais e uma nova era de sucesso, o Bragantino se destaca pela sua recente ascensão e pela sua moderna Arena, o Estádio Nabi Abi Chedid.",
        "linkhino": "https://www.letras.mus.br/hinos-de-futebol/383615/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Red_Bull_Bragantino",
        "linkSabiaMais": "https://www.transfermarkt.com.br/red-bull-bragantino/startseite/verein/8793",
        "titulos": {
            "estadual": 1,
            "nacional": 2,
            "internacional": 0
        },
        "imagemTime": "img/brasil_logos/bragantino.png", 
        "imagemEstadio": "img/brasil_estadios/bragantino_estadio.png",   
        "imagemMascote": "img/brasil_mascote/bragantino_mascote.png"  
    }, 
    {
        "nome": "Ceará",
        "alcunha": "Vozão",
        "anoInauguracao": "2 de junho de 1914 (110 anos)",
        "presidenteTime": "João Paulo Silva",
        "treinadorAtual": "Léo Condé", 
        "nomeEstadio": "Castelão (Estádio Governador Plácido Castelo)",
        "capacidade": 63904,
        "mascote": "Vovô",
        "historia": "O Ceará Sporting Club, fundado em 1914, é um dos clubes mais tradicionais do futebol cearense. Com uma história de conquistas estaduais e uma presença constante nas divisões principais do Campeonato Brasileiro, o Ceará é conhecido pela sua torcida apaixonada e pelo estádio Castelão, em Fortaleza.",
        "linkhino": "https://www.letras.mus.br/cearamor/hino-do-ceara/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Cear%C3%A1_Sporting_Club",
        "linkSabiaMais": "https://www.transfermarkt.com.br/ceara-sporting-club/startseite/verein/2029",
        "titulos": {
            "estadual": 48, 
            "nacional": 0,  
            "internacional": 0 
        },
        "imagemTime": "img/brasil_logos/ceara.png", 
        "imagemEstadio": "img/brasil_estadios/ceara_estadio.png", 
        "imagemMascote": "img/brasil_mascote/ceara_mascote.png"
    },
    {
        "nome": "Chapecoense",
        "alcunha": "Verdão do Oeste",
        "anoInauguracao": "10 de maio de 1973 (51 anos)",
        "presidenteTime": "Alex Passos",
        "treinadorAtual": "Tcheco", 
        "nomeEstadio": "Arena Condá",
        "capacidade": 22600,
        "mascote": "Índio Condá",
        "historia": "A Associação Chapecoense de Futebol, fundada em 1973, ganhou notoriedade nacional e internacional após uma tragédia aérea em 2016. Com uma história de superação, o clube é conhecido pelo seu forte desempenho no futebol catarinense e pelas suas recentes conquistas, incluindo a Copa Sul-Americana.",
        "linkhino": "https://www.letras.mus.br/hinos-de-futebol/663934/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Associa%C3%A7%C3%A3o_Chapecoense_de_Futebol",
        "linkSabiaMais": "https://www.transfermarkt.com.br/chapecoense/startseite/verein/17776",
        "titulos": {
          "estadual": 7,
          "nacional": 1, 
          "internacional": 1
        },
        "imagemTime": "img/brasil_logos/chapecoense.png", 
        "imagemEstadio": "img/brasil_estadios/chapecoense_estadio.png", 
        "imagemMascote": "img/brasil_mascote/chapecoense_mascote.png"
    },
    {
        "nome": "Corinthians",
        "alcunha": "Timão",
        "anoInauguracao": "1 de setembro de 1910 (114 anos)",
        "presidenteTime": "Augusto Melo",
        "treinadorAtual": "Ramón Díaz", 
        "nomeEstadio": "Neo Química Arena (Arena Corinthians)",
        "capacidade": 47605,
        "mascote": "Mosqueteiro",
        "historia": "O Sport Club Corinthians Paulista, fundado em 1910, é um dos clubes mais populares e vitoriosos do Brasil. Conhecido como Timão, o Corinthians possui uma vasta coleção de títulos, incluindo vários campeonatos brasileiros e a Copa Libertadores. O clube é famoso pela sua apaixonada torcida e pelo estádio Arena Corinthians.",
        "linkhino": "https://www.letras.mus.br/corinthians/1539059/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Sport_Club_Corinthians_Paulista",
        "linkSabiaMais": "https://www.transfermarkt.com.br/corinthians-sao-paulo/startseite/verein/199",
        "titulos": {
            "estadual": 30, 
            "nacional": 7,  
            "internacional": 4 
        },
        "imagemTime": "img/brasil_logos/corinthians.png", 
        "imagemEstadio": "img/brasil_estadios/corinthians_estadio.png", 
        "imagemMascote": "img/brasil_mascote/corinthians_mascote.png"
    },
    {
        "nome": "Cruzeiro",
        "alcunha": "Cabuloso",
        "anoInauguracao": "7 de outubro de 1942 (81 anos)",
        "presidenteTime": "Lidson Potsch",
        "treinadorAtual": "Fernando Seabra", 
        "nomeEstadio": "Mineirão",
        "capacidade": 62160,
        "mascote": "Rapoão",
        "historia": "O Cruzeiro Esporte Clube, fundado em 1921, é um dos clubes mais tradicionais e vitoriosos de Minas Gerais. Com uma rica história de conquistas nacionais e internacionais, o Cruzeiro é conhecido por suas vitórias na Libertadores e pela apaixonada torcida. O clube manda seus jogos no Estádio Mineirão.",
        "linkhino": "https://www.letras.mus.br/cruzeiro-esporte-clube/hino-do-cruzeiro/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Cruzeiro_Esporte_Clube",
        "linkSabiaMais": "https://www.transfermarkt.com.br/ec-cruzeiro-belo-horizonte/startseite/verein/609",
        "titulos": {
            "estadual": 39, 
            "nacional": 6,  
            "internacional": 5 
        },
        "imagemTime": "img/brasil_logos/cruzeiro.png", 
        "imagemEstadio": "img/brasil_estadios/cruzeiro_estadio.png", 
        "imagemMascote": "img/brasil_mascote/cruzeiro_mascote.png"
    },
    {
        "nome": "Figueirense",
        "alcunha": "Figueira",
        "anoInauguracao": "12 de junho de 1921 (103 anos)",
        "presidenteTime": "Paulo Prisco Paraíso",
        "treinadorAtual": "João Burse", 
        "nomeEstadio": "Estádio Orlando Scarpelli",
        "capacidade": 19584,
        "mascote": "Furacão",
        "historia": "O Figueirense Futebol Clube, fundado em 1921, é um dos clubes mais tradicionais de Santa Catarina. Conhecido como Furacão do Estreito, o Figueirense tem uma forte presença no futebol catarinense e é conhecido pela sua fiel base de torcedores e pelo Estádio Orlando Scarpelli.",
        "linkhino": "https://www.letras.mus.br/hinos-de-futebol/523393/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Figueirense_Futebol_Clube",
        "linkSabiaMais": "https://www.transfermarkt.com.br/figueirense-fc/startseite/verein/4064",
        "titulos": {
            "estadual": 17, 
            "nacional": 0,  
            "internacional": 0 
        },
        "imagemTime": "img/brasil_logos/figueirense.png", 
        "imagemEstadio": "img/brasil_estadios/figueirense_estadio.png", 
        "imagemMascote": "img/brasil_mascote/figueirense_mascote.png"
    },
    {
        "nome": "Flamengo",
        "alcunha": "Mengão",
        "anoInauguracao": "15 de novembro de 1895 (128 anos)",
        "presidenteTime": "Rodolfo Landim",
        "treinadorAtual": "Tite",
        "nomeEstadio": "Maracanã",
        "capacidade": 78838,
        "mascote": "Urubu",
        "historia": "O Clube de Regatas do Flamengo, fundado em 1895, é um dos clubes mais populares e vitoriosos do Brasil. Com uma enorme base de torcedores e uma rica tradição, o Flamengo possui diversos títulos nacionais e internacionais, incluindo a Copa Libertadores. O clube é famoso pelo Maracanã e pela paixão de sua torcida.",
        "linkhino": "https://www.letras.mus.br/hinos-de-futebol/46363/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Clube_de_Regatas_do_Flamengo",
        "linkSabiaMais": "https://www.transfermarkt.com.br/flamengo-rio-de-janeiro/startseite/verein/614",
        "titulos": {
            "estadual": 37, 
            "nacional": 8, 
            "internacional": 10 
        },
        "imagemTime": "img/brasil_logos/flamengo.png", 
        "imagemEstadio": "img/brasil_estadios/flamengo_estadio.png", 
        "imagemMascote": "img/brasil_mascote/flamengo_mascote.png"
    },
    {
        "nome": "Fluminense",
        "alcunha": "Tricolor das Laranjeiras",
        "anoInauguracao": "21 de julho de 1902 (122 anos)",
        "presidenteTime": "Mário Bittencourt",
        "treinadorAtual": "Mano Menezes", 
        "nomeEstadio": "Laranjeiras (Estádio Marcelo Vieira)",
        "capacidade": 8000,
        "mascote": "Cartola",
        "historia": "O Fluminense Football Club, fundado em 1902, é um dos clubes mais tradicionais do futebol brasileiro. Conhecido como Tricolor Carioca, o Fluminense possui uma rica história de conquistas e uma base de torcedores apaixonada. O clube manda seus jogos no Maracanã e tem uma história marcada por títulos estaduais e nacionais.",
        "linkhino": "https://www.letras.mus.br/fluminense/1574688/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Fluminense_Football_Club",
        "linkSabiaMais": "https://www.transfermarkt.com.br/fluminense-rio-de-janeiro/startseite/verein/2462",
        "titulos": {
            "estadual": 32,
            "nacional": 4,  
            "internacional": 1 
        },
        "imagemTime": "img/brasil_logos/fluminense.png", 
        "imagemEstadio": "img/brasil_estadios/fluminense_estadio.png", 
        "imagemMascote": "img/brasil_mascote/fluminense_mascote.png"
    },
    {
        "nome": "Fortaleza",
        "alcunha": "Laion, Tricolor de Aço",
        "anoInauguracao": "18 de outubro de 1918 (105 anos)",
        "presidenteTime": "Alex Santiago",
        "treinadorAtual": "Juan Pablo Vojvoda", 
        "nomeEstadio": "Castelão (Estádio Governador Plácido Castelo)",
        "capacidade": 63904,
        "mascote": "Leão",
        "historia": "O Fortaleza Esporte Clube, fundado em 1918, é um dos principais clubes do futebol nordestino. Conhecido como Leão do Pici, o Fortaleza tem uma base de torcedores fiel e realiza suas partidas no Estádio Castelão. O clube é conhecido por sua forte presença na Série A e suas conquistas estaduais.",
        "linkhino": "https://www.letras.mus.br/hinos-de-futebol/682806/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Associa%C3%A7%C3%A3o_Atl%C3%A9tica_Fortaleza",
        "linkSabiaMais": "https://www.transfermarkt.com.br/fortaleza-esporte-clube/startseite/verein/10870",
        "titulos": {
            "estadual": 43, 
            "nacional": 0,  
            "internacional": 0 
        },
        "imagemTime": "img/brasil_logos/fortaleza.png", 
        "imagemEstadio": "img/brasil_estadios/fortaleza_estadio.png", 
        "imagemMascote": "img/brasil_mascote/fortaleza_mascote.png"
    },
    {
        "nome": "Goiás",
        "alcunha": "Esmeraldino",
        "anoInauguracao": "6 de abril de 1943 (81 anos)",
        "presidenteTime": "Aroldo Guidão Filho",
        "treinadorAtual": "Vagner Mancini",
        "nomeEstadio": "Serra Dourada ou Serrinha (Estádio Hailé Pinheiro)",
        "capacidade": 14525,
        "mascote": "Periquito",
        "historia": "O Goiás Esporte Clube, fundado em 1943, é um dos principais clubes de Goiás. Com uma forte presença no futebol estadual e uma história de conquistas, o Goiás é conhecido pelo seu estádio, o Estádio da Serrinha. O clube tem uma torcida apaixonada e uma trajetória respeitável no Campeonato Brasileiro.",
        "linkhino": "https://www.letras.mus.br/hinos-de-futebol/1780776/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Goi%C3%A1s_Esporte_Clube",
        "linkSabiaMais": "https://www.transfermarkt.com.br/goias-ec/startseite/verein/3197",
        "titulos": {
            "estadual": 28, 
            "nacional": 0,  
            "internacional": 0 
        },
        "imagemTime": "img/brasil_logos/goias.png", 
        "imagemEstadio": "img/brasil_estadios/goias_estadio.png", 
        "imagemMascote": "img/brasil_mascote/goias_mascote.png"
    },
    {
        "nome": "Grêmio",
        "alcunha": "Imortal Tricolor",
        "anoInauguracao": "15 de setembro de 1903 (120 anos)",
        "presidenteTime": "Alberto Guerra",
        "treinadorAtual": "Renato Gaúcho",
        "nomeEstadio": "Arena do Grêmio",
        "capacidade": 60540,
        "mascote": "Mosqueteiro",
        "historia": "O Grêmio Foot-Ball Porto Alegrense, fundado em 1903, é um dos clubes mais tradicionais do futebol brasileiro. Com uma rica história de conquistas, incluindo títulos nacionais e internacionais, o Grêmio é conhecido por sua torcida apaixonada e pelo Estádio Arena do Grêmio. O clube é um dos maiores do sul do Brasil.",
        "linkhino": "https://www.letras.mus.br/hinos-de-futebol/402224/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Gr%C3%AAmio_Foot-Ball_Porto_Alegrense",
        "linkSabiaMais": "https://www.transfermarkt.com.br/gremio-porto-alegre/startseite/verein/210",
        "titulos": {
            "estadual": 39, 
            "nacional": 6,  
            "internacional": 3 
        },
        "imagemTime": "img/brasil_logos/gremio.png", 
        "imagemEstadio": "img/brasil_estadios/gremio_estadio.png", 
        "imagemMascote": "img/brasil_mascote/gremio_mascote.png"
    },
    {
        "nome": "Guarani",
        "alcunha": "Bugre",
        "anoInauguracao": "2 de abril de 1911 (113 anos)",
        "presidenteTime": "André Marconatto",
        "treinadorAtual": "Allan Aal", 
        "nomeEstadio": "Brinco de Ouro (Estádio Brinco de Ouro da Princesa)",
        "capacidade": 29130,
        "mascote": "Índio",
        "historia": "O Guarani Futebol Clube, fundado em 1911, é um dos clubes mais tradicionais de Campinas. Com uma história de conquistas estaduais e uma breve passagem pela Série A do Campeonato Brasileiro, o Guarani é conhecido pela sua base de torcedores fiel e pelo Estádio Brinco de Ouro.",
        "linkhino": "https://www.letras.mus.br/hinos-de-futebol/1213741/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Guarani_Futebol_Clube",
        "linkSabiaMais": "https://www.transfermarkt.com.br/guarani-fc-sp-/startseite/verein/1755",
        "titulos": {
            "estadual": 1,
            "nacional": 1,  
            "internacional": 0 
        },
        "imagemTime": "img/brasil_logos/guarani.png", 
        "imagemEstadio": "img/brasil_estadios/guarani_estadio.png", 
        "imagemMascote": "img/brasil_mascote/guarani_mascote.png"
    },
    {
        "nome": "Internacional",
        "alcunha": "Colorado",
        "anoInauguracao": "4 de abril de 1909 (115 anos)",
        "presidenteTime": "Alessandro Barcellos",
        "treinadorAtual": "Roger Machado", 
        "nomeEstadio": "Beira-Rio (Estádio José Pinheiro Borda)",
        "capacidade": 50128,
        "mascote": "Saci",
        "historia": "O Sport Club Internacional, fundado em 1909, é um dos clubes mais tradicionais do futebol brasileiro. Conhecido como Inter, o clube possui diversos títulos nacionais e internacionais, incluindo a Copa Libertadores. O Internacional é famoso pela sua torcida apaixonada e pelo Estádio Beira-Rio.",
        "linkhino": "https://www.letras.mus.br/internacional-rs/74177/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Sport_Club_Internacional",
        "linkSabiaMais": "https://www.transfermarkt.com.br/sc-internacional-porto-alegre/startseite/verein/6600",
        "titulos": {
            "estadual": 45, 
            "nacional": 7,  
            "internacional": 7 
        },
        "imagemTime": "img/brasil_logos/internacional.png", 
        "imagemEstadio": "img/brasil_estadios/internacional_estadio.png", 
        "imagemMascote": "img/brasil_mascote/internacional_mascote.png"
    },
    {
        "nome": "Náutico",
        "alcunha": "Timbu Coroado",
        "anoInauguracao": "7 de abril de 1901 (123 anos)",
        "presidenteTime": "Bruno Becker",
        "treinadorAtual": "Bruno Pivetti", 
        "nomeEstadio": "Aflitos (Estádio Eládio de Barros Carvalho)",
        "capacidade": 18694,
        "mascote": "Timbu",
        "historia": "O Clube Náutico Capibaribe, fundado em 1901, é um dos clubes mais tradicionais de Pernambuco. Com uma rica história no futebol local, o Náutico é conhecido pelo seu estádio, os Aflitos, e pela sua base de torcedores fiel. O clube tem uma trajetória marcada por conquistas estaduais.",
        "linkhino": "https://www.letras.mus.br/hinos-de-futebol/132781/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Clube_N%C3%A1utico_Capibaribe",
        "linkSabiaMais": "https://www.transfermarkt.com.br/clube-nautico-capibaribe/startseite/verein/2646",
        "titulos": {
            "estadual": 22, 
            "nacional": 0,  
            "internacional": 0 
        },
        "imagemTime": "img/brasil_logos/nautico.png", 
        "imagemEstadio": "img/brasil_estadios/nautico_esatadio.png", 
        "imagemMascote": "img/brasil_mascote/nautico_mascote.png"
    },
    {
        "nome": "Palmeiras",
        "alcunha": "Verdão",
        "anoInauguracao": "26 de agosto de 1914 (110 anos)",
        "presidenteTime": "Leila Pereira",
        "treinadorAtual": "Abel Ferreira", 
        "nomeEstadio": "Allianz Parque (antigo Arena Palestra Itália)",
        "capacidade": 43713,
        "mascote": "Periquito",
        "historia": "A Sociedade Esportiva Palmeiras, fundada em 1914, é um dos clubes mais vitoriosos do futebol brasileiro. Com uma rica história de conquistas, incluindo títulos nacionais e internacionais, o Palmeiras é conhecido pela sua torcida apaixonada e pelo Estádio Allianz Parque. O clube é conhecido pelo seu sucesso e tradição no futebol.",
        "linkhino": "https://www.letras.mus.br/palmeiras/397875/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Sociedade_Esportiva_Palmeiras",
        "linkSabiaMais": "https://www.transfermarkt.com.br/club-athletico-paranaense/startseite/verein/679",
        "titulos": {
            "estadual": 23,
            "nacional": 11,
            "internacional": 10 
        },
        "imagemTime": "img/brasil_logos/palmeiras.png", 
        "imagemEstadio": "img/brasil_estadios/palmeiras_estadio.png", 
        "imagemMascote": "img/brasil_mascote/palmeiras_mascote.png"
    },
    {
        "nome": "Paraná",
        "alcunha": "Paranista",
        "anoInauguracao": "19 de dezembro de 1989 (34 anos)",
        "presidenteTime": "Rubens Ferreira e Silva",
        "treinadorAtual": "Tcheco", 
        "nomeEstadio": "Vila Capanema (Estádio Durival Britto e Silva)",
        "capacidade": 17140,
        "mascote": "Gralha-azul",
        "historia": "O Paraná Clube, fundado em 1989, é um dos clubes mais importantes do futebol paranaense. Com uma forte presença no estado e uma trajetória de conquistas estaduais, o Paraná é conhecido pelo seu estádio, o Estádio Beira-Rio. O clube tem uma base de torcedores fiel e participa frequentemente das divisões principais do Campeonato Brasileiro.",
        "linkhino": "https://www.letras.mus.br/hinos-de-futebol/parana-clube/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Paran%C3%A1_Clube",
        "linkSabiaMais": "https://www.transfermarkt.com.br/parana-clube/startseite/verein/309",
        "titulos": {
            "estadual": 6, 
            "nacional": 0,  
            "internacional": 0 
        },
        "imagemTime": "img/brasil_logos/parana.png", 
        "imagemEstadio": "img/brasil_estadios/parana_estadio.png", 
        "imagemMascote": "img/brasil_mascote/parana_mascote.png"
    },
    {
        "nome": "Ponte Preta",
        "alcunha": "Macaca, Alvinegra de Campinas",
        "anoInauguracao": "11 de agosto de 1900 (124 anos)",
        "presidenteTime": "Marco Antônio Eberlin",
        "treinadorAtual": "Nelsinho Baptista", 
        "nomeEstadio": "Majestoso (Estádio Moisés Lucarelli",
        "capacidade": 17728,
        "mascote": "Macaca",
        "historia": "A Associação Ponte Preta, fundada em 1900, é um dos clubes mais tradicionais de Campinas. Conhecida como Macaca, a Ponte Preta possui uma rica história no futebol paulista e uma base de torcedores apaixonada. O clube realiza suas partidas no Estádio Moisés Lucarelli e tem uma trajetória respeitável no futebol brasileiro.",
        "linkhino": "https://www.letras.mus.br/hinos-de-futebol/77224/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Associa%C3%A7%C3%A3o_Atl%C3%A9tica_Ponte_Preta",
        "linkSabiaMais": "https://www.transfermarkt.com.br/aa-ponte-preta/startseite/verein/1134",
        "titulos": {
            "estadual": 0, 
            "nacional": 0,  
            "internacional": 0 
        },
        "imagemTime": "img/brasil_logos/ponte_preta.png", 
        "imagemEstadio": "img/brasil_estadios/ponte_preta_estadio.png", 
        "imagemMascote": "img/brasil_mascote/ponte_preta_mascote.png"
    },
    {
        "nome": "Santos",
        "alcunha": "Peixão, Alvinegro Praiano",
        "anoInauguracao": "14 de abril de 1912 (112 anos)",
        "presidenteTime": "Marcelo Texeira",
        "treinadorAtual": "Fábio Carille",
        "nomeEstadio": "Vila Belmiro (Estádio Urbano Caldeira)",
        "capacidade": 20360,
        "mascote": "Baleião",
        "historia": "O Santos Futebol Clube, fundado em 1912, é um dos clubes mais tradicionais e vitoriosos do Brasil. Com uma rica história de conquistas, incluindo títulos nacionais e internacionais, o Santos é conhecido pela sua base de torcedores fiel e pelo Estádio Vila Belmiro. O clube é famoso pela sua história de sucesso e pelos grandes jogadores que revelou.",
        "linkhino": "https://www.letras.mus.br/hinos-de-futebol/78601/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Santos_Futebol_Clube",
        "linkSabiaMais": "https://www.transfermarkt.com.br/fc-santos/startseite/verein/221",
        "titulos": {
            "estadual": 22,
            "nacional": 8,  
            "internacional": 3 
        },
        "imagemTime": "img/brasil_logos/santos.png", 
        "imagemEstadio": "img/brasil_estadios/santos_estadio.png", 
        "imagemMascote": "img/brasil_mascote/santos_mascote.png"
    },
    {
        "nome": "São Paulo",
        "alcunha": "Tricolor Paulista",
        "anoInauguracao": "25 de janeiro de 1930 (94 anos)",
        "presidenteTime": "Juio Casares",
        "treinadorAtual": "Luis Zubeldía", 
        "nomeEstadio": "MorumBIS (Estádio Cícero Pompeu de Toledo)",
        "capacidade": 66795,
        "mascote": "Santo Paulo",
        "historia": "O São Paulo Futebol Clube, fundado em 1930, é um dos clubes mais vitoriosos do Brasil. Com diversos títulos nacionais e internacionais, o São Paulo é conhecido pela sua torcida apaixonada e pelo Estádio do Morumbi. O clube tem uma história rica no futebol brasileiro e mundial.",
        "linkhino": "https://www.letras.mus.br/sao-paulo-futebol-clube/1076561/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/S%C3%A3o_Paulo_Futebol_Clube",
        "linkSabiaMais": "https://www.transfermarkt.com.br/fc-sao-paulo/startseite/verein/585",
        "titulos": {
            "estadual": 21, 
            "nacional": 6, 
            "internacional": 12 
        },
        "imagemTime": "img/brasil_logos/sao_paulo.png", 
        "imagemEstadio": "img/brasil_estadios/sao_paulo_estadio.png", 
        "imagemMascote": "img/brasil_mascote/sao_paulo_mascote.png"
    },
    {
        "nome": "Sport",
        "alcunha": "Leão da Ilha",
        "anoInauguracao": "13 de maio de 1905 (119 anos)",
        "presidenteTime": "Yuri Romão",
        "treinadorAtual": "Pepa", 
        "nomeEstadio": "Ilha do Retiro (Estádio Adelmar da Costa Carvalho",
        "capacidade": 26418,
        "mascote": "Leão",
        "historia": "O Sport Club do Recife, fundado em 1905, é um dos clubes mais tradicionais do futebol nordestino. Conhecido como Leão, o Sport tem uma forte presença no futebol pernambucano e nacional, com diversos títulos estaduais e uma Copa do Brasil. O clube realiza suas partidas na Arena Pernambuco e possui uma base de torcedores fiel.",
        "linkhino": "https://www.letras.mus.br/hinos-de-futebol/127728/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Sport_Club_do_Recife",
        "linkSabiaMais": "https://www.transfermarkt.com.br/sport-club-do-recife/startseite/verein/8718",
        "titulos": {
            "estadual": 42, 
            "nacional": 1,  
            "internacional": 0 
        },
        "imagemTime": "img/brasil_logos/sport.png", 
        "imagemEstadio": "img/brasil_estadios/sport_estadio.png", 
        "imagemMascote": "img/brasil_mascote/sport_mascote.png"
    },
    {
        "nome": "Vasco",
        "alcunha": "Gigante da Colina",
        "anoInauguracao": "21 de agosto de 1898 (126 anos)",
        "presidenteTime": "Pedrinho",
        "treinadorAtual": "Rafael Paiva", 
        "nomeEstadio": "São Januário (Estádio Vasco da Gama)",
        "capacidade": 21880 ,
        "mascote": "Dom Corvo I",
        "historia": "O Club de Regatas Vasco da Gama, fundado em 1898, é um dos clubes mais tradicionais do futebol brasileiro. Com uma rica história de conquistas, incluindo títulos nacionais e internacionais, o Vasco é conhecido pela sua torcida apaixonada e pelo Estádio São Januário. O clube tem uma trajetória marcante no futebol brasileiro.",
        "linkhino": "https://www.letras.mus.br/lamartine-babo/216966/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Club_de_Regatas_Vasco_da_Gama",
        "linkSabiaMais": "https://www.transfermarkt.com.br/schnellsuche/ergebnis/schnellsuche?query=vasco",
        "titulos": {
            "estadual": 24,
            "nacional": 4, 
            "internacional": 1 
        },
        "imagemTime": "img/brasil_logos/vasco.png", 
        "imagemEstadio": "img/brasil_estadios/vasco_estadio.png", 
        "imagemMascote": "img/brasil_mascote/vasco_mascote.png"
    },
    {
        "nome": "Vitória",
        "alcunha": "Leão da Barra",
        "anoInauguracao": "13 de maio de 1899 (125 anos)",
        "presidenteTime": "Fábio Mota",
        "treinadorAtual": "Thiago Carpini", 
        "nomeEstadio": "Barradão (Estádio Manoel Barradas)",
        "capacidade": 30793,
        "mascote": "Leão",
        "historia": "O Esporte Clube Vitória, fundado em 1899, é um dos principais clubes da Bahia. Com uma história de conquistas estaduais e uma presença respeitável no futebol brasileiro, o Vitória é conhecido pelo seu estádio, o Barradão, e pela sua base de torcedores fiel. O clube tem uma trajetória marcada por sucesso no futebol baiano.Fundado em 1899, o Vitória é um dos clubes mais importantes da Bahia, conhecido por suas conquistas e pela paixão de seus torcedores.",
        "linkHino": "https://www.letras.mus.br/hinos-de-futebol/1779601/",
        "linkMaisInfo": "https://pt.wikipedia.org/wiki/Esporte_Clube_Vit%C3%B3ria",
        "linkSabiaMais": "https://www.transfermarkt.com.br/esporte-clube-vitoria/startseite/verein/2125",
        "titulos": {
            "estadual": 29, 
            "nacional": 1,  
            "internacional": 0 
        },
        "imagemTime": "img/brasil_logos/vitoria.png", 
        "imagemEstadio": "img/brasil_estadios/vitoria_estadio.png", 
        "imagemMascote": "img/brasil_mascote/vitoria_mascote.png"
    }
];
